Repository ViniciusDeep/Revill, pull requests merged in 2019-10, with the labels that each got.

#6 Updated Readme.md look
  README.md
Labels: Hacktoberfest, Process

#8 Service layer basic implementation
  Revill/Revill/API/Providey.swift
  Revill/Revill/Settings/AppDelegate.swift
  Revill/Revill/View/Feed/CategoriesView.swift
  Revill/Revill/View/Feed/SearchView.swift
Labels: Dev, Hacktoberfest

#11 Implement CI
  Revill/.travis.yml
Labels: Devops, Hacktoberfest

#14 Create component at horizontal list of categories like (Swift UI)
  Revill/Revill/View/Feed/CategoriesView.swift
Labels: Dev, Hacktoberfest, SwiftUI

#15 [PR] - Games list
  Revill/Revill.xcodeproj/project.pbxproj
  Revill/Revill/API/Providey.swift
  Revill/Revill/Settings/AppDelegate.swift
  Revill/Revill/Settings/SceneDelegate.swift
  Revill/Revill/View/Feed/CategoriesView.swift
  Revill/Revill/View/Feed/ContentView.swift
  Revill/Revill/View/Feed/HighlightedCardView.swift
  Revill/Revill/View/Feed/ListOfGames.swift
  Revill/Revill/View/Feed/RowGames.swift
  Revill/Revill/View/Feed/SearchView.swift
Labels: Dev, Hacktoberfest, SwiftUI

#17 Implemented the search view and created a search field component
  Revill/Revill.xcodeproj/project.pbxproj
  Revill/Revill/Assets.xcassets/search-icon.imageset/Contents.json
  Revill/Revill/Assets.xcassets/search-icon.imageset/search-icon (1).png
  Revill/Revill/Assets.xcassets/search-icon.imageset/search-icon.png
  Revill/Revill/Fonts/Nunito-Black.ttf
  Revill/Revill/Fonts/Nunito-Bold.ttf
  Revill/Revill/Fonts/Nunito-Regular.ttf
  Revill/Revill/Info.plist
  Revill/Revill/View/Feed/SearchField.swift
  Revill/Revill/View/Feed/SearchView.swift
Labels: Dev, Hacktoberfest, SwiftUI
